# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='voted_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='issues.Issue'),
        ),
    ]
