# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190801_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
