# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('town_or_city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_number', models.IntegerField()),
                ('total_paid', models.IntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
            ],
        ),
    ]
