# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-10 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='details',
            new_name='payment_details',
        ),
    ]
