# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
