# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
