# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='views',
        ),
    ]
