# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentBlog',
        ),
    ]
