# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190806_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='updated',
        ),
    ]
