# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcomment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
