# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category_update',
            field=models.DateTimeField(null=True),
        ),
    ]
