# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='tag',
        ),
    ]
