# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_commentfeatures_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfeatures',
            name='user_votes',
            field=models.IntegerField(default=0),
        ),
    ]
